#!/bin/bash
cat /etc/passwd
echo "##"
echo "# Host Database"
echo "#"
echo "# localhost is used to configure the loopback interface"
echo "# when the system is booting. Do not change this entry."
echo "##"
cat /etc/hosts
